name: Docker Image CI

on:
  push:
    branches: [ "CI_Fix" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Node Build React For Release
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - 
      name: Download Dependencies
      run: |
        cd application
        npm run install-server
        npm run install-frontend
        cd frontend
        npm run build
        node ./scripts/move.js

    # -
    #   name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # -
    #   name: Set Up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    # -
    #   name: Build and Push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: ./application/backend
    #     file: ./application/backend/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/csc648_seal_team_one:latest
    
